[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python backend/manage.py collectstatic --no-input"
]

[start]
cmd = "python backend/manage.py migrate && gunicorn --chdir backend config.wsgi:application"
