# Generated by Django 5.0.6 on 2026-06-12 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('facultad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('documento_identidad', models.FileField(upload_to='solicitudes/identidad/')),
                ('comprobante_matricula', models.FileField(upload_to='solicitudes/matricula/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones_admin', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Verificación',
                'verbose_name_plural': 'Solicitudes de Verificación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('postulante', 'Postulante'), ('evaluador', 'Evaluador'), ('administrador', 'Administrador')], default='postulante', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('registro', 'Registro de postulante'), ('evaluacion', 'Evaluación realizada'), ('reevaluacion_masiva', 'Reevaluación masiva'), ('modificar_postulante', 'Modificación de datos de postulante'), ('modificar_parametro', 'Modificación de parámetro'), ('crear_convocatoria', 'Creación de convocatoria'), ('modificar_convocatoria', 'Modificación de convocatoria'), ('exportar', 'Exportación de datos'), ('crear_usuario', 'Creación de usuario'), ('modificar_usuario', 'Modificación de usuario'), ('otro', 'Otra acción')], max_length=50, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='usuarios_lo_usuario_9171f9_idx'), models.Index(fields=['accion', 'timestamp'], name='usuarios_lo_accion_c20457_idx')],
            },
        ),
    ]
