# Generated by Django 5.0.6 on 2026-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudverificacion',
            name='boleta_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/boletas/', verbose_name='Boleta de Inscripción'),
        ),
        migrations.AddField(
            model_name='solicitudverificacion',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Registro'),
        ),
    ]
