# Generated by Django 5.0.6 on 2026-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudverificacion_boleta_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudverificacion',
            name='comprobante_matricula',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/matricula/'),
        ),
        migrations.AlterField(
            model_name='solicitudverificacion',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/identidad/'),
        ),
    ]
