# Generated by Django 5.0.6 on 2026-06-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0014_remove_postulante_solicitud_verificacion_and_more'),
        ('usuarios', '0003_alter_solicitudverificacion_comprobante_matricula_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudVerificacion',
        ),
    ]
