# Generated by Django 5.0.6 on 2026-06-12 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
        ('postulantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_academico', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje académico')),
                ('puntaje_socioeconomico', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje socioeconómico')),
                ('puntaje_total', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('evaluado', 'Evaluado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del evaluador')),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='convocatorias.convocatoria', verbose_name='Convocatoria')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='postulantes.postulante', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-puntaje_total'],
                'indexes': [models.Index(fields=['estado', 'puntaje_total'], name='evaluacione_estado_d8585e_idx')],
            },
        ),
    ]
