# Generated by Django 5.0.6 on 2026-06-12 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Identificador único (ej: peso_academico)', max_length=100, unique=True, verbose_name='Nombre del parámetro')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Parámetro de Beca',
                'verbose_name_plural': 'Parámetros de Beca',
                'ordering': ['nombre'],
            },
        ),
    ]
