# Generated by Django 5.0.6 on 2026-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.IntegerField(verbose_name='Desde (materias)')),
                ('hasta', models.IntegerField(blank=True, help_text='Dejar vacío para representar infinito / "o más"', null=True, verbose_name='Hasta (materias)')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
            ],
            options={
                'verbose_name': 'Rango de Materias',
                'verbose_name_plural': 'Rangos de Materias',
                'ordering': ['desde'],
            },
        ),
        migrations.CreateModel(
            name='RangoPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.FloatField(verbose_name='Desde (promedio)')),
                ('hasta', models.FloatField(verbose_name='Hasta (promedio)')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
            ],
            options={
                'verbose_name': 'Rango de PPS',
                'verbose_name_plural': 'Rangos de PPS',
                'ordering': ['desde'],
            },
        ),
        migrations.CreateModel(
            name='ReglaDesempate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Regla')),
                ('campo_modelo', models.CharField(max_length=100, verbose_name='Campo de la Ficha/Postulante/Solicitud')),
                ('orden_ejecucion', models.PositiveIntegerField(default=1, verbose_name='Orden de Ejecución')),
                ('direccion', models.CharField(choices=[('asc', 'Ascendente'), ('desc', 'Descendente')], default='desc', max_length=10, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Regla de Desempate',
                'verbose_name_plural': 'Reglas de Desempate',
                'ordering': ['orden_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='OpcionSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(choices=[('dependencia', 'Dependencia Económica (X1)'), ('ocupacion', 'Tipo de Ocupación (X2)'), ('rango_ingresos', 'Rango de Ingresos (X3)'), ('num_integrantes', 'Número de Integrantes (X4)'), ('num_hijos', 'Número de Hijos (X5)'), ('lugar_residencia', 'Lugar de Residencia (X6)'), ('tenencia_vivienda', 'Tenencia de Vivienda (X7)'), ('tipo_vivienda', 'Tipo de Vivienda (X8)'), ('procedencia', 'Lugar de Procedencia (X9)')], max_length=50, verbose_name='Variable')),
                ('opcion_texto', models.CharField(max_length=200, verbose_name='Texto de la Opción')),
                ('puntaje', models.IntegerField(default=0, verbose_name='Puntaje')),
            ],
            options={
                'verbose_name': 'Opción Socioeconómica',
                'verbose_name_plural': 'Opciones Socioeconómicas',
                'ordering': ['variable', '-puntaje'],
                'unique_together': {('variable', 'opcion_texto')},
            },
        ),
    ]
