# Generated by Django 5.0.6 on 2026-06-19

from django.db import migrations

def split_parent_option(apps, schema_editor):
    OpcionSocioeconomica = apps.get_model('parametros', 'OpcionSocioeconomica')
    FichaSocioeconomica = apps.get_model('postulantes', 'FichaSocioeconomica')
    
    # 1. Update existing FichaSocioeconomica records
    # Change "Solo padre o madre" to "Solo padre"
    FichaSocioeconomica.objects.filter(dependencia='Solo padre o madre').update(dependencia='Solo padre')

    # 2. Update OpcionSocioeconomica options
    # Delete "Solo padre o madre"
    OpcionSocioeconomica.objects.filter(variable='dependencia', opcion_texto='Solo padre o madre').delete()

    # Create "Solo padre" if not exists
    OpcionSocioeconomica.objects.get_or_create(
        variable='dependencia',
        opcion_texto='Solo padre',
        defaults={'puntaje': 9}
    )

    # Create "Solo madre" if not exists
    OpcionSocioeconomica.objects.get_or_create(
        variable='dependencia',
        opcion_texto='Solo madre',
        defaults={'puntaje': 9}
    )

def reverse_split(apps, schema_editor):
    OpcionSocioeconomica = apps.get_model('parametros', 'OpcionSocioeconomica')
    FichaSocioeconomica = apps.get_model('postulantes', 'FichaSocioeconomica')

    # Revert FichaSocioeconomica records
    FichaSocioeconomica.objects.filter(dependencia__in=['Solo padre', 'Solo madre']).update(dependencia='Solo padre o madre')

    # Revert OpcionSocioeconomica
    OpcionSocioeconomica.objects.filter(variable='dependencia', opcion_texto__in=['Solo padre', 'Solo madre']).delete()
    OpcionSocioeconomica.objects.get_or_create(
        variable='dependencia',
        opcion_texto='Solo padre o madre',
        defaults={'puntaje': 9}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_rangomaterias_rangopps_regladesempate_and_more'),
        ('postulantes', '0015_alter_datosacademicos_certificado_notas_pdf_and_more'),
    ]

    operations = [
        migrations.RunPython(split_parent_option, reverse_split),
    ]
