# Generated by Django 5.0.6 on 2026-06-19 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_split_parent_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SemestreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Periodo académico cuyos datos están registrando los postulantes. Ej: 2025-2', max_length=20, verbose_name='Semestre Activo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Semestre de Registro',
                'verbose_name_plural': 'Semestre de Registro',
            },
        ),
        migrations.CreateModel(
            name='MateriaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_academico', models.CharField(help_text='Periodo académico al que pertenece esta materia. Ej: 2025-2, 2026-1', max_length=20, verbose_name='Semestre Académico')),
                ('sigla', models.CharField(max_length=15, verbose_name='Sigla')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Materia')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_catalogo', to='parametros.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia del Catálogo',
                'verbose_name_plural': 'Catálogo de Materias',
                'ordering': ['orden', 'sigla'],
                'unique_together': {('carrera', 'semestre_academico', 'sigla')},
            },
        ),
    ]
