# Generated by Django 5.0.6 on 2026-06-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='comprobante_ingresos',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='contrato_alquiler',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='creditos_aprobados',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='creditos_totales',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='es_cabeza_hogar',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='estrato',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='ingreso_familiar',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='num_hermanos_universidad',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='numero_personas_hogar',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='recibo_servicios',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tipo_vivienda',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='trabaja',
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_respaldo_ingreso',
            field=models.FileField(blank=True, null=True, upload_to='respaldos/ingresos/', verbose_name='Archivo de respaldo de ingreso'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='barrio_residencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='calle_residencia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='cantidad_hijos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='¿Cuántos?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='certificado_procedencia',
            field=models.FileField(blank=True, null=True, upload_to='respaldos/procedencia/', verbose_name='Certificado/acreditación de procedencia'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='comentario_personal',
            field=models.TextField(blank=True, verbose_name='Aclaración o comentario personal'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='cual_beneficio',
            field=models.CharField(blank=True, max_length=200, verbose_name='¿Cuál beneficio?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='dependencia',
            field=models.CharField(blank=True, choices=[('independiente', 'Independiente'), ('solo_padre_madre', 'Solo padre o madre'), ('otro_familiar', 'Otro familiar'), ('pareja', 'De la pareja'), ('ambos_padres', 'Ambos padres')], max_length=50, verbose_name='De quien depende?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_bano',
            field=models.BooleanField(default=False, verbose_name='Baño'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_comedor',
            field=models.BooleanField(default=False, verbose_name='Comedor'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_dormitorio',
            field=models.BooleanField(default=False, verbose_name='Dormitorio'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_patio',
            field=models.BooleanField(default=False, verbose_name='Patio'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_sala',
            field=models.BooleanField(default=False, verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='lugar_procedencia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de procedencia'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='numero_celular_personal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de celular personal'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Registro'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='ocupacion_dependencia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ocupación de quien depende'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='otro_beneficio',
            field=models.BooleanField(default=False, verbose_name='¿Tiene otro beneficio dentro de la universidad?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='prov_residencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia (Residencia)'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='rango_ingresos',
            field=models.CharField(blank=True, choices=[('menor_2500', 'Menor de Bs. 2500.-'), ('2501_4000', 'De Bs. 2501 a Bs. 4000.-'), ('4001_6000', 'De Bs. 4001 a Bs. 6000.-'), ('mas_6000', 'Más de Bs. 6000.-')], max_length=20, verbose_name='Ingresos'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='respaldo_vivienda',
            field=models.FileField(blank=True, null=True, upload_to='respaldos/vivienda/', verbose_name='Respaldo de vivienda'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='telefono_referencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de teléfono de referencia'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tiene_discapacidad',
            field=models.BooleanField(default=False, verbose_name='¿Tiene algún tipo de discapacidad?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tiene_hijos',
            field=models.BooleanField(default=False, verbose_name='¿Tiene hijos?'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tipo_grado_discapacidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipo y Grado'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tipo_respaldo_ingreso',
            field=models.CharField(blank=True, choices=[('asalariado_formal', 'Asalariado formal (Fotocopia boleta de pago)'), ('asalariado_informal', 'Asalariado informal (Declaración jurada)'), ('comerciante_mayorista', 'Comerciante mayorista (Fotocopia NIT)'), ('rentista', 'Rentista (Fotocopia Boleta)'), ('comerciante_minorista', 'Comerciante minorista (NIT/Carnet socio)'), ('agricultor', 'Agricultor (Carnet socio/Nota)')], max_length=50, verbose_name='Tipo de Respaldo'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tipo_tenencia',
            field=models.CharField(blank=True, choices=[('herencia', 'Herencia'), ('de_padres', 'De los padres'), ('cedida', 'Cedida'), ('anticretico', 'Anticrético'), ('alquiler', 'Alquiler')], max_length=50, verbose_name='Tipo de tenencia'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='zona_anillo_residencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zona o Anillo'),
        ),
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='carrera',
            field=models.CharField(blank=True, max_length=200, verbose_name='Carrera'),
        ),
        migrations.CreateModel(
            name='MiembroFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('parentesco', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('ocupacion', models.CharField(max_length=200, verbose_name='Ocupación')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_familiares', to='postulantes.fichasocioeconomica')),
            ],
            options={
                'verbose_name': 'Miembro Familiar',
                'verbose_name_plural': 'Miembros Familiares',
            },
        ),
    ]
