# Generated by Django 5.0.6 on 2026-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_remove_fichasocioeconomica_comprobante_ingresos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='infra_descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción de cuartos (ej. 2 cuartos, compartido, etc.)'),
        ),
    ]
