# Generated by Django 5.0.6 on 2026-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0003_fichasocioeconomica_infra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='archivo_boleta_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/boletas/', verbose_name='Boleta de inscripción'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='archivo_carnet_identidad',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/carnets/', verbose_name='Carnet de identidad'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='archivo_historico_academico',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/historicos/', verbose_name='Histórico académico'),
        ),
    ]
