# Generated by Django 5.0.6 on 2026-06-12 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
        ('postulantes', '0004_postulante_archivo_boleta_inscripcion_and_more'),
        ('usuarios', '0002_solicitudverificacion_boleta_inscripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pps', models.FloatField(help_text='Promedio Ponderado Acumulado (0-100)')),
                ('materias_aprobadas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Datos Académicos',
                'verbose_name_plural': 'Datos Académicos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.FloatField(blank=True, null=True)),
                ('puntaje_academico', models.FloatField(blank=True, null=True)),
                ('puntaje_socioeconomico', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Beca',
                'verbose_name_plural': 'Solicitudes de Beca',
            },
        ),
        migrations.AlterModelOptions(
            name='postulante',
            options={'verbose_name': 'Postulante', 'verbose_name_plural': 'Postulantes'},
        ),
        migrations.RemoveIndex(
            model_name='postulante',
            name='postulantes_cedula_3fc8e1_idx',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='archivo_respaldo_ingreso',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='barrio_residencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='calle_residencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='cantidad_hijos',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='certificado_procedencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='comentario_personal',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='cual_beneficio',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_bano',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_comedor',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_descripcion',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_dormitorio',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_patio',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='infra_sala',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='lugar_procedencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='numero_celular_personal',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='numero_registro',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='ocupacion_dependencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='prov_residencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='respaldo_vivienda',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='telefono_referencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tiene_discapacidad',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tiene_hijos',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tipo_grado_discapacidad',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tipo_respaldo_ingreso',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='tipo_tenencia',
        ),
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='zona_anillo_residencia',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='archivo_boleta_inscripcion',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='archivo_carnet_identidad',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='archivo_historico_academico',
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='descripcion_otro_beneficio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='discapacidad',
            field=models.CharField(blank=True, help_text='Escribir tipo y grado si aplica', max_length=200),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='doc_ingresos',
            field=models.FileField(blank=True, upload_to='fichas/ingresos/'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='doc_ocupacion',
            field=models.FileField(blank=True, upload_to='fichas/ocupacion/'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='doc_vivienda',
            field=models.FileField(blank=True, upload_to='fichas/vivienda/'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='fecha_llenado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='lugar_residencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='num_hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='num_integrantes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='procedencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tenencia_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='tipo_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='solicitud_verificacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.solicitudverificacion'),
        ),
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='otro_beneficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='postulante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_socioeconomica', to='postulantes.postulante'),
        ),
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='rango_ingresos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes', to='convocatorias.convocatoria'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='datos_completos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='ficha_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='postulante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to='postulantes.postulante'),
        ),
        migrations.AddField(
            model_name='solicitudbeca',
            name='postulante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_beca', to='postulantes.postulante'),
        ),
    ]
