# Generated by Django 5.0.6 on 2026-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0005_datosacademicos_solicitudbeca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_boleta_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='fichas/boletas/'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_carnet_identidad',
            field=models.FileField(blank=True, null=True, upload_to='fichas/identidades/'),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_historico_academico',
            field=models.FileField(blank=True, null=True, upload_to='fichas/historicos/'),
        ),
    ]
