# Generated by Django 5.0.6 on 2026-06-17 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0006_fichasocioeconomica_archivo_boleta_inscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosacademicos',
            old_name='pps',
            new_name='ppa',
        ),
        migrations.CreateModel(
            name='MateriaSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('semestre', models.CharField(default='2025-1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='postulantes.postulante')),
            ],
            options={
                'verbose_name': 'Materia Cursada',
                'verbose_name_plural': 'Materias Cursadas',
                'ordering': ['semestre', 'sigla'],
            },
        ),
    ]
