# Generated by Django 5.0.6 on 2026-06-17 01:14

import apps.postulantes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0007_rename_pps_datosacademicos_ppa_materiasemestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosacademicos',
            name='certificado_notas_pdf',
            field=models.FileField(blank=True, help_text='Certificado de notas del semestre pasado (PDF)', null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.postulantes.models.validate_file_size]),
        ),
    ]
