# Generated by Django 5.0.6 on 2026-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0008_datosacademicos_certificado_notas_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosacademicos',
            name='puntaje_academico_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='puntaje_materias',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='puntaje_ppa',
            field=models.FloatField(default=0.0),
        ),
    ]
