# Generated by Django 5.0.6 on 2026-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0009_datosacademicos_puntaje_academico_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbeca',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudbeca',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudbeca',
            name='observaciones_internas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
