# Generated by Django 5.0.6 on 2026-06-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0010_solicitudbeca_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbeca',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudbeca',
            name='notificado_rechazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudbeca',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
