# Generated by Django 5.0.6 on 2026-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0011_solicitudbeca_fecha_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichasocioeconomica',
            name='ocupacion',
            field=models.CharField(default='', help_text='Escribe tu ocupación o trabajo actual', max_length=100),
        ),
    ]
