# Generated by Django 5.0.6 on 2026-06-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0012_alter_fichasocioeconomica_ocupacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichasocioeconomica',
            name='discapacidad',
        ),
    ]
