# Generated by Django 5.0.6 on 2026-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0013_remove_fichasocioeconomica_discapacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='solicitud_verificacion',
        ),
        migrations.AddField(
            model_name='postulante',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postulante',
            name='facultad',
            field=models.CharField(blank=True, default='Facultad Integral de los Valles Cruceños', max_length=100),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
