# Generated by Django 5.0.6 on 2026-06-19 01:22

import apps.postulantes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0014_remove_postulante_solicitud_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicos',
            name='certificado_notas_pdf',
            field=models.FileField(blank=True, help_text='Certificado de notas del semestre pasado (PDF o Imagen)', null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']), apps.postulantes.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='materiasemestre',
            name='semestre',
            field=models.CharField(default='2025-2', max_length=20),
        ),
    ]
