# Generated by Django 5.0.6 on 2026-06-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0015_alter_datosacademicos_certificado_notas_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='semestre_actual',
            field=models.CharField(blank=True, default='', help_text='Semestre que cursas actualmente (ej: 2026-1)', max_length=20, verbose_name='Semestre Actual'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingeniería en Sistemas', 'Ingeniería en Sistemas'), ('Ingeniería Agropecuaria', 'Ingeniería Agropecuaria'), ('Contaduría Pública', 'Contaduría Pública'), ('Industrialización de Alimentos', 'Industrialización de Alimentos')], default='', max_length=100),
        ),
    ]
