# Generated by Django 5.0.6 on 2026-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0016_add_semestre_actual_carrera_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_analisis_medicos',
            field=models.FileField(blank=True, null=True, upload_to='fichas/medicos/'),
        ),
    ]
