# Generated by Django 5.0.6 on 2026-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0017_fichasocioeconomica_archivo_analisis_medicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='archivo_carnet_identidad_reverso',
            field=models.FileField(blank=True, null=True, upload_to='fichas/identidades/'),
        ),
    ]
