# Generated by Django 5.0.6 on 2026-06-25 19:41

import apps.postulantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0018_fichasocioeconomica_archivo_carnet_identidad_reverso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicos',
            name='certificado_notas_pdf',
            field=models.FileField(blank=True, help_text='Certificado de notas del semestre pasado (PDF o Imagen)', null=True, upload_to='certificados/', validators=[apps.postulantes.models.validate_file_size]),
        ),
    ]
